import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-09T04:00:00Z') })
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'NOT_CONFIGURED', message: '未配置' } } }))
  await page.goto('/')
  await page.getByRole('button', { name: '查看日期与黄历详情' }).click()
})

test('二级日历完整显示与 iTab 实测当天一致的信息，本地离线计算', async ({ page }) => {
  const dialog = page.getByRole('dialog', { name: '日历', exact: true })
  const detail = page.getByRole('region', { name: '所选日期详情' })
  for (const value of ['2026-10-09 周五', '二〇二六年八月廿九', '丙午(马)年', '本年第41周，第282天', '天秤座', '祭祀，解除，破屋，坏垣，馀事勿取', '诸事不宜', '残月', '鸿雁来宾', '喜神方位：西南', '阳贵神方位：西', '阴贵神方位：西北', '福神方位：东', '财神方位：西南']) await expect(detail).toContainText(value)
  await expect(dialog.getByRole('button', { name: /2026-10-01 国庆节 休/ })).toBeVisible()
  await expect(dialog.getByRole('button', { name: /2026-10-10 九月 班/ })).toBeVisible()
  await expect(dialog.getByRole('button', { name: /2026-10-08 寒露/ })).toBeVisible()
  await expect(dialog.getByRole('button', { name: /2026-10-31 万圣夜/ })).toBeVisible()
  await expect(dialog.getByText('工具', { exact: true })).toHaveCount(0)
  await page.context().setOffline(true)
  await dialog.getByRole('button', { name: /2026-10-18 重阳节/ }).click()
  for (const value of ['2026-10-18 周日', '二〇二六年九月初九', '重阳节', '本年第42周，第291天', '还有9天', '蛾眉月', '菊有黄花']) await expect(detail).toContainText(value)
  await expect(dialog.getByRole('button', { name: /2026-10-09 廿九/ })).toHaveAttribute('aria-current', 'date')
  await expect(dialog.getByRole('button', { name: /2026-10-18 重阳节/ })).toHaveAttribute('aria-pressed', 'true')
})

test('年月、周起始日、相邻月与回到今天保持日期和详情一致', async ({ page }) => {
  const dialog = page.getByRole('dialog')
  const detail = page.getByRole('region', { name: '所选日期详情' })
  await dialog.getByRole('switch', { name: '一周从周一开始' }).click()
  await expect(detail).toContainText('本年第41周')
  await dialog.getByRole('button', { name: /2026-10-18 重阳节/ }).click()
  await expect(detail).toContainText('本年第43周')
  await dialog.getByRole('button', { name: '下个月', exact: true }).click()
  await expect(detail).toContainText('2026-11-01 周日')
  await dialog.getByLabel('月份', { exact: true }).selectOption('12')
  await expect(detail).toContainText('2026-12-01')
  await dialog.getByRole('button', { name: '下个月', exact: true }).click()
  await expect(detail).toContainText('2027-01-01')
  // 尚无 2027 年官方数据时不从周末或节日推测休班。
  await expect(dialog.getByRole('button', { name: '2027-01-01 元旦', exact: true })).toBeVisible()
  await dialog.getByLabel('年份', { exact: true }).fill('2026')
  await dialog.getByLabel('年份', { exact: true }).press('Enter')
  await dialog.getByLabel('月份', { exact: true }).selectOption('10')
  await dialog.getByRole('button', { name: /2026-11-01 万圣节/ }).click()
  await expect(dialog.getByLabel('月份', { exact: true })).toHaveValue('11')
  await expect(detail).toContainText('2026-11-01')
  await dialog.getByRole('button', { name: '今', exact: true }).click()
  await expect(detail).toContainText('2026-10-09')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: '查看日期与黄历详情' })).toBeFocused()
  await page.reload()
  await page.getByRole('button', { name: '查看日期与黄历详情' }).click()
  await expect(page.getByRole('switch', { name: '一周从周一开始' })).toHaveAttribute('aria-checked', 'false')
})

test('桌面和手机日历可展开与关闭，没有横向溢出', async ({ page }) => {
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 954 })
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    const box = await dialog.boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width)
    if (width === 1440) expect(box!.width).toBeGreaterThan(1000)
    expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await dialog.getByRole('button', { name: '展开日历窗口' }).click()
    const expanded = await dialog.boundingBox()
    expect(expanded!.width).toBe(width)
    await dialog.getByRole('button', { name: '恢复日历窗口' }).click()
  }
})


test('历法缺日和年份边界仍能安全导航', async ({ page }) => {
  const dialog = page.getByRole('dialog')
  const year = dialog.getByLabel('年份', { exact: true })
  const month = dialog.getByLabel('月份', { exact: true })
  const detail = page.getByRole('region', { name: '所选日期详情' })
  await year.fill('1582')
  await year.press('Enter')
  await expect(detail).toContainText('1582-01-01')
  await month.selectOption('10')
  await expect(detail).toContainText('1582-10-01')
  await expect(dialog.getByRole('button', { name: /^1582-10-0[5-9]/ })).toHaveCount(0)
  await dialog.getByRole('button', { name: /^1582-10-31 / }).click()
  await month.selectOption('9')
  await expect(detail).toContainText('1582-09-01')
  await month.selectOption('10')
  await expect(detail).toContainText('1582-10-01')
  await year.fill('3')
  await year.press('Enter')
  await month.selectOption('1')
  await expect(dialog.getByRole('button', { name: '上个月', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: /^0002-/ })).toHaveCount(0)
  await year.fill('9998')
  await year.press('Enter')
  await month.selectOption('12')
  await expect(dialog.getByRole('button', { name: '下个月', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: /^9999-/ })).toHaveCount(0)
  await dialog.getByRole('button', { name: '今', exact: true }).click()
  await expect(detail).toContainText('2026-10-09')
})

test('月历滚轮逐月切换，母亲节显示本地计算的节日', async ({ page }) => {
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('月份', { exact: true }).selectOption('5')
  await dialog.getByRole('button', { name: /2026-05-10 母亲节/ }).click()
  await expect(page.getByRole('region', { name: '所选日期详情' })).toContainText('母亲节')
  await dialog.locator('.calendar-month-grid').hover()
  await page.mouse.wheel(0, 100)
  await expect(page.getByRole('region', { name: '所选日期详情' })).toContainText('2026-06-01')
  await expect(dialog.getByRole('button', { name: /2026-06-21 父亲节/ })).toBeVisible()
})
