import { expect, test } from '@playwright/test'

test('正式首页显示独立日期与 UTC 时差，设置刷新后保留', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-05T16:10:00Z') })
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'LifeSpace', exact: true })).toBeVisible()
  await expect(page.getByText('原型 · 示例数据')).toHaveCount(0)
  const time = page.getByRole('button', { name: '查看世界时间详情' })
  await expect(time).toContainText('UTC+8')
  await expect(time).toContainText('UTC-4')
  await expect(time).toContainText('UTC+1')
  await expect(time).toContainText('10月6日星期二')
  await expect(time).toContainText('10月5日星期一')
  await expect(time).not.toContainText('昨日')
  await page.getByRole('button', { name: '首页设置', exact: true }).click()
  await page.getByLabel('东京', { exact: true }).check()
  await page.getByLabel('加尔各答', { exact: true }).check()
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(time).toContainText('另有 2 个时区')
  await page.reload()
  await page.getByRole('button', { name: '查看世界时间详情' }).click()
  await expect(page.getByRole('dialog')).toContainText('东京')
  await expect(page.getByRole('dialog')).toContainText('UTC+5:30')
})

test('Google 搜索支持 Enter 和按钮，空关键词保持当前页面', async ({ page, context }) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  await context.route('https://www.google.com/search?**', route => route.fulfill({ body: '搜索结果' }))
  await page.goto('/')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  expect(context.pages()).toHaveLength(1)
  for (const trigger of ['enter', 'button']) {
    await page.getByRole('textbox', { name: 'Google 搜索' }).fill('LifeSpace 中文 搜索')
    const popupPromise = page.waitForEvent('popup')
    if (trigger === 'enter') await page.getByRole('textbox', { name: 'Google 搜索' }).press('Enter')
    else await page.getByRole('button', { name: '搜索', exact: true }).click()
    const popup = await popupPromise
    await popup.waitForURL('https://www.google.com/search?**')
    expect(new URL(popup.url()).searchParams.get('q')).toBe('LifeSpace 中文 搜索')
    await popup.close()
  }
})

test('电脑和手机布局无横向溢出，导航占位保持禁用', async ({ page }) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 954 })
    await page.goto('/')
    const dimensions = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth }))
    expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport)
    for (const name of ['任务管理', '个人目标', '财务', '股票行情']) await expect(page.getByRole('button', { name, exact: true })).toBeDisabled()
    await page.getByRole('button', { name: '打开设置' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
})

test('黄历摘要和已打开详情在本地午夜切换到同一天', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-05T15:59:00Z') })
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  await page.goto('/')
  const calendar = page.getByRole('button', { name: '查看日期与黄历详情' })
  await expect(calendar).toContainText('八月廿五')
  await calendar.click()
  await expect(page.getByRole('dialog')).toContainText('八月廿五')
  await page.clock.fastForward(120000)
  await expect(page.getByRole('dialog')).toContainText('八月廿六')
  await page.getByRole('button', { name: '关闭详情' }).click()
  await expect(calendar).toContainText('八月廿六')
})

test('手机显示较长城市名称时，地点与 UTC 时差仍为单行', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  await page.goto('/')
  await page.getByRole('button', { name: '打开设置' }).click()
  await page.getByLabel('纽约', { exact: true }).uncheck()
  await page.getByLabel('加尔各答', { exact: true }).check()
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  const city = await page.getByText('加尔各答', { exact: true }).boundingBox()
  const offset = await page.getByText('UTC+5:30', { exact: true }).boundingBox()
  expect(city).not.toBeNull(); expect(offset).not.toBeNull()
  expect(city!.height).toBeLessThan(20)
  expect(Math.abs(city!.y - offset!.y)).toBeLessThan(6)
})

test('纽约夏令时开始后，UTC 时差和当地时钟同步前进一小时', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-03-08T06:59:00Z') })
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: { code: 'TASKS_NOT_CONFIGURED', message: '任务来源尚未配置' } } }))
  await page.goto('/')
  const card = page.getByRole('button', { name: '查看世界时间详情' })
  await expect(card).toContainText('01:59')
  await expect(card).toContainText('UTC-5')
  await page.clock.fastForward(120000)
  await expect(card).toContainText('03:01')
  await expect(card).toContainText('UTC-4')
})
