/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: d6e4601a5e547d429de8a8e01645f655)
interface __BaseEnv_CloudflareEnv {
	DNSHE_READ_LIMITER: RateLimit;
	NEWS_READ_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_SECRET_KEY: string;
	DNSHE_API_KEY: string;
	DNSHE_API_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_SECRET_KEY" | "DNSHE_API_KEY" | "DNSHE_API_SECRET">> {}
}
