#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 本项目流程：只配置本地 DNSHE 凭据。
set +x
umask 077
cd "$(dirname "$0")/.."
ENV_FILE=".dev.vars"
TOTAL_STAGES=2
trap 'unset DNSHE_API_KEY DNSHE_API_SECRET' EXIT

# 中文界面适配位于 STAGES 区；上方通用库保持原样。
pause() {
  printf '  %s ' "${1:-按 Enter 继续：}"
  if ! IFS= read -r _; then
    say "输入已结束，配置取消。"
    exit 1
  fi
}
banner() {
  _clear
  printf '\n  LifeSpace · DNSHE 本地凭据配置（共 %s 步）\n\n' "$TOTAL_STAGES"
  say "凭据仅写入本地 .dev.vars，输入隐藏。"
  say "可随时按 Ctrl-C 退出。"
  pause "按 Enter 开始："
}
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n  第 %s/%s 步 · %s\n\n' "$_STAGE_INDEX" "$TOTAL_STAGES" "$1"
}
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  # 兼容模板和已有 .dev.vars 中带引号的单行值。
  if [[ "$current" == \"*\" || "$current" == \'*\' ]]; then
    current="${current:1:${#current}-2}"
  fi
  printf '  %s' "$prompt"
  [[ -z "$current" ]] || printf '（Enter 保留已保存的值）'
  printf '：'
  if ! IFS= read -rs input; then
    printf '\n'
    say "输入已结束，配置取消。"
    exit 1
  fi
  printf '\n'
  [[ -n "$input" || -z "$current" ]] || input="$current"
  printf -v "$key" '%s' "$input"
}
finish() {
  _clear
  say "已保存 DNSHE_API_KEY 和 DNSHE_API_SECRET 到本地 .dev.vars。"
  say "文件权限为 600，原有其他配置已保留。"
  say "请重新启动本项目开发服务，使凭据生效。"
  say "配置完成后回复 Codex：已配置。下一步核验真实读取结果。"
}

if [[ ! -t 0 || ! -t 1 ]]; then
  printf '请在交互式终端运行 npm run setup:dnshe，凭据不接受管道输入。\n' >&2
  exit 1
fi
if [[ -L "$ENV_FILE" || ( -e "$ENV_FILE" && ! -f "$ENV_FILE" ) ]]; then
  printf '.dev.vars 必须是本项目中的普通文件，未修改配置。\n' >&2
  exit 1
fi
if ! git check-ignore -q "$ENV_FILE" || git ls-files --error-unmatch "$ENV_FILE" >/dev/null 2>&1; then
  printf '.dev.vars 未被 Git 安全忽略，未修改配置。\n' >&2
  exit 1
fi

banner
stage "获取并输入凭据"
open_url "https://my.dnshe.com/index.php?m=domain_hub" >/dev/null
step "打开 https://my.dnshe.com/index.php?m=domain_hub 并登录。"
step "进入免费域名管理 → API 管理。"
step "复制已有 API Key 和 API Secret；若没有，点击创建 API Key，并保存显示的 Secret。"
note "官方指引：https://api005.dnshe.com/knowledgebase/13/DNSHE-Free-Domain-API-User-Guide-V2.0.html"
while true; do
  ask_secret DNSHE_API_KEY "粘贴 API Key（输入隐藏）"
  if [[ "$DNSHE_API_KEY" =~ ^cfsd_[A-Za-z0-9_-]+$ ]]; then break; fi
  say "API Key 应以 cfsd_ 开头，请重新粘贴。"
done
while true; do
  ask_secret DNSHE_API_SECRET "粘贴 API Secret（输入隐藏）"
  if [[ "$DNSHE_API_SECRET" =~ ^[A-Za-z0-9_./+=:-]+$ ]]; then break; fi
  say "Secret 不能为空或包含空白、引号等不支持字符，请重新粘贴。"
done

stage "保存本地配置"
write_env DNSHE_API_KEY "$DNSHE_API_KEY" >/dev/null
chmod 600 "$ENV_FILE"
write_env DNSHE_API_SECRET "$DNSHE_API_SECRET" >/dev/null
chmod 600 "$ENV_FILE"
unset DNSHE_API_KEY DNSHE_API_SECRET
finish
